name: Vanilla Plasma
id: plasma
vibversion: 1.1.0

stages:
- id: build
  base: ghcr.io/vanilla-kde/base:dev
  addincludes: true
  singlelayer: false
  labels:
    maintainer: Fangcat_Dev
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
  cleanup:
    - /boot/initrd.img*
    - /tmp/*
    - /var/cache/apt/pkgcache.bin
    - /var/cache/debconf
    - /var/cache/dictionaries-common
    - /var/cache/fontconfig
    - /var/cache/ldconfig
    - /var/cache/man
    - /var/lib/dbus/machine-id
    - /var/log/*

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt update
    - apt clean
    - apt-mark hold plasma-discover-backend-snap

  - name: packages-modules
    type: includes
    includes:
      - modules/00-vanilla-backgrounds.yml
      - modules/15-plasma-essentials.yml
      - modules/17-plasma-apps.yml
      - modules/997-misc-setup.yml
      - modules/999-cleanup.yml

  - name: cleanup-and-sysconf-setup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - lpkg --lock